### ISSUE TITLE
Check possibilities to sync enums between frontend and backend

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#111] opened 2022-04-10 18:36 UTC
Do research whether it is possible to share enums between frontend and backend to simplify their synchronisation

**Comment by han16nah** [comment] 2022-04-24 08:18
If possible to share, we can convert enum representation to frontend representation by replacing underscore with space and having the first letter capitalized.

**Comment by sami1riaz** [comment] 2023-02-18 16:54
closing as this is a duplicate of #239 now

**Closed by sami1riaz** 2023-02-18 16:54 UTC
Labels: research, Prio:LOW
