### ISSUE TITLE
Do not show the tabs “electricity” and “heating” to non-representatives on 'Add emissions' page

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#306] opened 2023-05-23 20:27 UTC
Do not show the tabs “electricity” and “heating” to non-representatives on 'Add emissions' page, since they are not able to enter data anyways.

**Comment by codingfabi** [comment] 2023-05-29 08:34
Duplicate of #292

**Closed as completed by codingfabi** 2023-05-29 08:34 UTC
Labels: frontend
